---
abstract: 'minimalistic lint for perl'
author:
  - 'KOBAYASHI, Hiroaki <hkoba@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perlminlint
provides:
  App::perlminlint:
    file: lib/App/perlminlint.pm
    version: 0.1
  App::perlminlint::Object:
    file: lib/App/perlminlint/Object.pm
  App::perlminlint::Plugin:
    file: lib/App/perlminlint/Plugin.pm
  App::perlminlint::Plugin::LintCPANfile:
    file: lib/App/perlminlint/Plugin/LintCPANfile.pm
  App::perlminlint::Plugin::LintPL:
    file: lib/App/perlminlint/Plugin/LintPL.pm
  App::perlminlint::Plugin::LintPM:
    file: lib/App/perlminlint/Plugin/LintPM.pm
  App::perlminlint::Plugin::LintT:
    file: lib/App/perlminlint/Plugin/LintT.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
