#!/usr/bin/env perl
use strict;
use warnings FATAL => qw/all/;

use FindBin;
BEGIN {
  # To allow using plugins from PERL5LIB.
  push @INC, grep {-d} "$FindBin::Bin/../lib"
}

use App::perlminlint;

App::perlminlint->run(\@ARGV);
